language: node_js
branches:
  - master
jobs:
  include:
    - stage: CI_test
      node_js: 8
      language: node_js
      cache:
        yarn: true
        directories:
          - node_modules
          - "$HOME/.npm"
          - $HOME/.yarn-cache
      script:
        - yarn lint
        - yarn test
        - yarn build
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build
