language: node_js
node_js: 10
branches:
  - master
jobs:
  include:
    - stage: CI
      if: |
        branch = master AND \
        type = pull_request
      cache:
        yarn: true
        directories:
          - node_modules
          - "$HOME/.npm"
          - "$HOME/.yarn-cache"
      script:
        - yarn lint
        - yarn test
        - yarn build
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build
    - stage: CD
      if: |
        branch = master AND \
        type = push
      before_script:
        - echo "//npm.pkg.github.com/:_authToken=" > ./.npmrc
        - echo $ACCESS_TOKEN >> ./.npmrc
        - cat ./.npmrc.conf >> ./.npmrc
      script:
        - yarn publish

